Update Neovim installation to use latest version

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -300,10 +300,12 @@ if [[ -n "${CODESPACES:-}" ]]; then
   run_command tar -xvzf /tmp/tokei-x86_64-unknown-linux-gnu.tar.gz -C /tmp
   run_command sudo mv /tmp/tokei /usr/bin/tokei
 
-  # Install the latest neovim
-  run_command wget https://github.com/neovim/neovim/releases/download/v0.10.0/nvim.appimage
-  run_command chmod u+x nvim.appimage
-  run_command sudo mv nvim.appimage /usr/local/bin/nvim
+  VERSION=$(curl -fsSL https://api.github.com/repos/neovim/neovim/releases/latest | jq -r '.tag_name')
+  [ -n "$VERSION" ] || { run_command echo "Failed to resolve Neovim version" >&2; exit 1; }
+  APPURL="https://github.com/neovim/neovim/releases/download/${VERSION}/nvim-linux-x86_64.appimage"
+  run_command wget -q --show-progress --progress=bar:force:noscroll "$APPURL"
+  run_command chmod u+x nvim-linux-x86_64.appimage
+  run_command sudo mv nvim-linux-x86_64.appimage /usr/local/bin/nvim
 
   if ! [ -x "$(command -v npm)" ]; then
     log "WARN" 'Could not install node neovim plugin' >&2
